/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.finecloud.flink.scala-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))

    implementation("org.apache.flink:flink-connector-kafka:1.16.0")
    implementation("org.apache.flink:flink-java:1.16.0")
    implementation("org.apache.flink:flink-clients:1.16.0")

    implementation("org.slf4j:slf4j-api:2.0.6")
    implementation("redis.clients:jedis:4.3.1")
    implementation("com.mysql:mysql-connector-j:8.0.31")
    implementation("org.jetbrains:annotations:24.0.0")

    implementation("org.apache.hbase:hbase-client:2.5.2")
    implementation("org.apache.hbase:hbase-server:2.5.2")


    compileOnly("org.apache.flink:flink-jdbc_2.12:1.10.3")
    compileOnly("org.apache.flink:flink-connector-hive_2.12:1.16.0")
    compileOnly("org.apache.flink:flink-streaming-java:1.16.0")


    testImplementation("org.slf4j:slf4j-log4j12:2.0.6")

}

application {
    // Define the main class for the application.
    mainClass.set("com.finecloud.flink.app.App")
}
